### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by adinos** [pipacs/ionic#40]
Example: http://download.jw.org/files/media_books/es12_E.epub 

There are blue "hyperlinks" to verses, but if i touch them, nothing happens...

I use Ionic 0.6.0 on a Nokia N8 with Symbian Belle

Thank you, adino

**Comment by pipacs** [comment]
Anchors are disabled due to a Nokia bug: https://bugs.webkit.org/show_bug.cgi?id=48415 . Let's see if there is a workaround.

**Comment by pipacs** [comment]
Worked around in 0.6.5.
