### ISSUE TITLE
Baterry consumes too fast. Need black background.

### ISSUE THREAD

**Issue by tzaq93** [pipacs/ionic#45]
Hello,

I know that this is a free app and I don't have the right to request stuff but I would suggest to add an option to choose between the black-text-white-background and the white-text-black-background themes. This because it is not possible to enjoy reading on a Nokia C7 for example without the fear of running out of juice. We should take advantage of the Clear Black screen that uses less power to show black pixels than white ones.

Thank you, sir!

**Comment by pipacs** [comment]
Select the Night theme from Settings.

**Comment by tzaq93** [comment]
Oh I didn't scroll down in settings to see this option. My bad. Thank you very much!

-----Mesaj original-----
De la: Akos Polster
Exped.:  01-04-2012, 22:30 
Către: tzaq93
Subiect: Re: [ionic] Baterry consumes too fast. Need black background. (#45)

Select the Night theme from Settings.

---
