### ISSUE TITLE
Night mode background is not 100% black

### ISSUE THREAD

**Issue by SLAYER33** [pipacs/ionic#46]
Reading using night mode (in a lit room at night), you can see a blue tent in the background behind the text. I took some screenshots to compare the colors and found that the background used isn't 100% black. 
this doesn't appear in the settings/library/bookmarks, only while reading.

here is a few comparisons, also included is a screenshot from albite reader, if you want to compare on a phone screen.

http://i87.photobucket.com/albums/k155/slayer_333_2006/Untitled-1-2.jpg
http://i87.photobucket.com/albums/k155/slayer_333_2006/Untitled-2-1.jpg

http://i87.photobucket.com/albums/k155/slayer_333_2006/Scr000114.jpg
http://i87.photobucket.com/albums/k155/slayer_333_2006/Scr000117.jpg

http://i87.photobucket.com/albums/k155/slayer_333_2006/Scr000118.jpg
http://i87.photobucket.com/albums/k155/slayer_333_2006/Scr000118-brightnes-increased-in-PS.jpg  
^^Increased brightness using photoshop, albite reader stays black

**Comment by pipacs** [comment]
Fixed in 0.6.4.
