### ISSUE TITLE
Make swipe up/down move exactly one page

### ISSUE THREAD

**Issue by mattleech** [pipacs/ionic#50]
Running v0.6.3 which I just downloaded from Nokia Store, on N8 Belle.

Please change the swipe up/down to move one page exactly.

Maybe also add swipe left/right to have the same functionality.

Thanks,
Matt

**Comment by pipacs** [comment]
The toolbar arrows and the volume keys implement exactly this functionality. To activate the volume keys, select "Navigate with volume keys" from Settings.

**Comment by mattleech** [comment]
Hi,

Sorry, I should have put more detail into my previous message.

Yes, the page up/down function is implemented currently with the toolbar icons but when you're reading it's inconvenient to have to glance down to an icon to turn the page, it'd be better with a swipe action as this can be done anywhere on screen.

I am also aware that the volume button can be used to page up/down and even though there's no need to look for this control it's not a comfortable physical action.

These are just my thoughts, the app is still great :)

Thanks,
Matt

**Comment by pipacs** [comment]
I understand the need, it's just swipe might not be the best gesture for this. I'm experimenting with alternative solutions, stay tuned :)
